MERCHANTS = [
    "Amazon",
    "Flipkart",
    "Myntra",
    "Ajio",
    "Reliance Digital",
    "Croma",
    "Tata Cliq",
    "Swiggy",
    "Zomato",
    "Dominos",
    "Pizza Hut",
    "Uber",
    "Ola",
    "IRCTC",
    "MakeMyTrip",
    "Yatra",
    "Goibibo",
    "BookMyShow",
    "JioMart",
    "BigBasket",
    "DMart",
    "Nykaa",
    "FirstCry",
    "Meesho",
    "Paytm Mall",
    "Snapdeal",
    "Lifestyle",
    "Shoppers Stop",
    "PVR",
    "INOX",
    "Apollo Pharmacy",
    "MedPlus",
    "NetMeds",
    "Tanishq",
    "KFC",
    "Burger King",
    "Starbucks",
    "McDonalds",
    "Samsung Store",
    "Apple Store",
    "Vijay Sales",
    "Poorvika",
    "Decathlon",
    "Mochi",
    "Max Fashion",
    "Pantaloons",
    "Westside",
    "Trends",
    "Metro Shoes",
    "Home Centre"
]